### ISSUE TITLE
Cannot configure automatic language switching in multispeech server to work with emacspeak

### ISSUE THREAD

**Issue by sevapopov2** [tvraman/emacspeak#107]
Hello,
I have a following issue.
I try to set up Emacspeak on Arch with [multispeech server](https://github.com/poretsky/multispeech) developed by Igor Poretsky.
This is the multilingual speech server that allows to switch between languages on the fly. For example it can switch between English and Russian languages while reading. It also supports a lot of other languages such as Spanish, French, German, Italian and Portuguese.
I tried to set this up manually with Emacspeak from master branch on Debian and Arch but the problem is that when running Emacs the server doesn't switch languages.
As described in [this issue](https://github.com/poretsky/multispeech/issues/1) I do the following steps to compile and launch things:
1. Compile multispeech.
2. Clone Emacspeak from this repository and compile it.
3. Compile [ru_tts](https://github.com/poretsky/ru_tts) and [rulex dictionary for ru_tts](https://github.com/poretsky/rulex)
4. Put the following in ~/.multispeechrc

```
# Setting up speech settings for multispeech.
[speech]
language = autodetect
fallback = ru
[en]
engine = mbrola
[ru]
engine = ru_tts
[de]
engine = disabled
[fr]
engine = disabled
[es]
engine = disabled
[it]
engine = disabled
[pt]
engine = disabled

[mbrola]
voices = /usr/share/mbrola
```

6. Copy the compiled multispeech server from /usr/local/bin/multispeech to /home/user/emacspeak-path/servers.
7. Test multispeech server by typing:

```
multispeech
q Hello
d
q привет
d
```

Language switches.
8. Set the following variable in my .zshrc:

```
export DTK_PROGRAM=multispeech
```

10. Set the following in /home/user/.emacs.d/init.el:

```
(load-file "/home/seva/Apps/emacspeak/lisp/emacspeak-setup.el")
```

11. Launch Emacs by issuing emacs command in terminal.
When encountering Russian text it should switch to Russian synthesizer, but it doesn't switch the language.
However, if I install pre-built packages for Debian 11 that are available and described [here](https://poretsky.github.io/packages/) everything works as expected. I suppose the problem is in emacspeak configuration that I have...
I tried so many things but I cannot find any way to fix this.
Thank you.

**Comment by tvraman** [comment]
this is not presently supported. Design and patches welcome

**Comment by sevapopov2** [comment]
Hello @tvraman, 
Thank you for your reply.
Here are some things that I have figured out:
When multispeech server is enabled on emacspeak from master, other languages are supported but not Russian (E.G. server can switch to Spanish text without any issues, however when switching to Russian text it doesn't perform the switch and remains on English/Spanish TTS).
It seems like there are patches needed to implement Russian language support for Emacspeak. I know that Igor Poretsky has such, but they work only on Debian/Ubuntu distributions.
Would it be possible to consider including these patches in upstream? That would really help other users like me who prefer Arch to configure the environment for using emacs on several languages like Russian and English at the same time. Thank you!

**Comment by tvraman** [comment]
Depends on where the patches need to be applie.
1. the multispeech server is not part of the emacspeak project or its
   git repo
2. So you should first ask Igor where they belong.
3. If some patch belongs in the emacspeak project, first create a
   minimal PR.
4. If that PR is checked in, who will maintain/test it?
5. We can decide how to help Russian users once we figure out the above.
   
--

**Comment by sevapopov2** [comment]
Hello @tvraman, 
Here is what I could find out.
1. Yes, it is true that multispeech is not the part of emacspeak repository but it can be found and installed from [here](https://github.com/poretsky/multispeech).
2. All patches for multispeech and unicode support are made by Igor as well as a lot of other useful patches that he did and they are located in his emacspeak fork's folder. Here is [the patch for multispeech support](https://github.com/poretsky/emacspeak/blob/jammy/debian/patches/0024-Multispeech-support.patch) and here is the [better unicode support patch](https://github.com/poretsky/emacspeak/blob/jammy/debian/patches/0029-Better-unicode-support.patch).
However I cannot seem to find a way to apply these patches to the newest version of emacspeak to check that these are in fact 2 right patches to apply and they are enough for making Russian language to work.
I would really like these patches to be applied to upstream because they would allow not only Debian and Ubuntu users but also Arch and other systems to use emacspeak in Russian. I didn't find any way to use Russian espeak with emacspeak so this would be really appriciated.
What steps can I perform towards applying the patches to the newest version to check that they work?
Thank you!

**Comment by tvraman** [comment]
I suggest the following:

1. He create a Github PR based on his work, but against the latest Git Snapshot.
2. That he publish that PR on the  Emacspeak list.
3. That he responds to feedback there, and fixes any issues.
4. When we are past that, we can consider next steps.
5. Personally I'd prefer that he creates and maintains an independent
   Russian-support package once the minimal set of changes to Emacspeak
   have been integrated
6. The above is because I cannot maintain the Russian support because I
   can neither read nor write it, and it'll go stale unless someone who
   is passionate about it owns it.
   
--
