### ISSUE TITLE
chrome_tts_server no longer works with modern chrome

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#115]
The message you get if you try to install it is:

"Chrome TTS Server" is no longer supported

Old versions of Chrome apps won't open on Mac devices after
December 2022. You can check if there's a new version available.

----

Now, it is a very neat project and I looked at ways to save it but basically it would be a complete rewrite, can't convert to extension because it uses sockets and can't continue to use it as an app.

**Comment by tvraman** [comment]
There are no plans to support this.
--

**Comment by robertmeta** [comment]
Yep, I almost submitted a PR to remove it, but couldn't find anything about the policy towards cool but no longer usable servers.

It still has valuable info in there about the Chrome TTS stuff, even if the stocket and so forth isn't going to work anymore.

**Comment by tvraman** [comment]
1. Robert, We set up the Emacspeak mail list with a lot of effort for a
   reason, and we explicitly decided that Github lists were not the
   answer. Please respect that decision.
2. The Chrome server has met its purpose and is mostly educational at
   this point
3. It's not deleted it's in the attic.
4. For a project with now 30 years of history, periodic cleaning is
   essential for it to survive and thrive
   
Robert Melton ***@***.***> writes:

> Yep, I almost submitted a PR to remove it, but couldn't find anything
> about the policy towards cool but no longer usable servers.
>
> It still has valuable info in there about the Chrome TTS stuff, even
> if the stocket and so forth isn't going to work anymore.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
>

--

**Comment by tvraman** [comment]
"T.V Raman" ***@***.***> writes:


P.S. Could you look into seeing if it is possible to have email
generated via Github issues to be automatically copied to the emacspeak
mailing list?

I use Github exclusively through the command-line gh utility, and I dont
see a way of doing it, there may be a way via the Web site that is a
one-time config setup
> 1. Robert, We set up the Emacspeak mail list with a lot of effort for a
>    reason, and we explicitly decided that Github lists were not the
>    answer. Please respect that decision.
> 2. The Chrome server has met its purpose and is mostly educational at
>    this point
> 3. It's not deleted it's in the attic.
> 4. For a project with now 30 years of history, periodic cleaning is
>    essential for it to survive and thrive
>    
> Robert Melton ***@***.***> writes:
>
>> Yep, I almost submitted a PR to remove it, but couldn't find anything
>> about the policy towards cool but no longer usable servers.
>>
>> It still has valuable info in there about the Chrome TTS stuff, even
>> if the stocket and so forth isn't going to work anymore.
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you commented.
>>

--

**Comment by robertmeta** [comment]
Sure, relatively easy to do with workflows, and all setup is just via the workflow yaml and gh command line tool to setup a few secrets. 

Will do a PR for it. 


> On Feb 28, 2024, at 11:54, T. V. Raman ***@***.***> wrote:
> 
> P.S. Could you look into seeing if it is possible to have email
> generated via Github issues to be automatically copied to the emacspeak
> mailing list?

--
Robert Melton
***@***.***

**Comment by tvraman** [comment]
Thanks Robert!
--
