### ISSUE TITLE
Cannot reproduce the audio examples on a Ubuntu 2204 Gnome Desktop with Google Chrome

### ISSUE THREAD

**Issue by paaguti** [tvraman/emacspeak#121]
Hi, with the recent addition to auto-completion hints for text modes, which I find too intrusive, I was trying to understand how they would betreated with emacspeak. However, I'm not able to reproduce the auto-complete example. It just is a series of unintelligible squeeks...

**Comment by tvraman** [comment]
I dont have  sufficient info here to follow what you're
saying. Emacspeak does not support the auto-complete package.

--

**Comment by tvraman** [comment]
not relevant
