### ISSUE TITLE
[Feature Request] Make RHVoice compatibility

### ISSUE THREAD

**Issue by zenny** [tvraman/emacspeak#134]
Hi @tvraman 

I suggest to make RHVoice (https://github.com/RHVoice/RHVoice) compatible with emacspeak because the quality of voice is far more better than festival and others among the open source TTSes. The software works via `speech-disptacher` in GNU/Linux. Installation is very straight forward as stated in https://github.com/RHVoice/RHVoice/blob/master/doc/en/Compiling-on-Linux.md

Cheers and have a nice weekend,
/zenny

**Comment by zenny** [comment]
Just noted a similar request in the RHVoice issue tracker in https://github.com/RHVoice/RHVoice/issues/102, fyi. Thanks.

**Comment by tvraman** [comment]
feel free to self-organize toward this goal, aka in a manner similar to what was done for  swiftmac

**Comment by zenny** [comment]
> feel free to self-organize toward this goal, aka in a manner similar to what was done for swiftmac

I am new to everything and I felt like `piper` which has already been supported is a good choice. Yet I shall try if `emacspeak` works at my end. 

Thanks again @tvraman.

Cheers,
zenny
