### ISSUE TITLE
eSpeak NG unsupported, regular eSpeak unmaintained

### ISSUE THREAD

**Issue by devinprater** [tvraman/emacspeak#19]
A next-generation, free software synthesizer, eSpeak-NG, should be supported by Emacspeak. Now that Aurolux charges money for Voxin, a proprietary synthesizer which is no longer even free to download, eSpeak, and possibly fLite, are the only developed speech synthesizers. Yet, these speech servers are the most neglected out of all of them, with even the stable version of the regular eSpeak package not having support, in Emacspeak, to switch to other languages besides the default English-UK. With one of eSpeak’s main advantages being it’s diverse language selection, I’d hope that Emacspeak could take advantage of this. Furthermore, Emacspeak doesn’t seem to be able to change voice pitch or “variant” to show voice-lock or aural CSS. This is a sad state, as going forward, Espeak-NG may be the only speech synthesizer which is updated. I see a future for Emacspeak, which is why I file this issue, rather than work with Speechd-el, which is more suited for low-vision users or very advanced users with plenty of time on their hands. Perhaps a server for speech-dispatcher could be made, or the existing eSpeak server could be modified to work with eSpeak-NG.  What happens, though, I hope that a future is secured for Emacspeak in the realm of updated speech synthesizers on Linux.

**Comment by tvraman** [comment]
patches welcome, trolling ignored

**Comment by tvraman** [comment]
closed: install espeak-ng compat libs
