### ISSUE TITLE
failing (and proposed fix for) emacspeak-setup.el on Emacs 25.1.1, Fedora 24

### ISSUE THREAD

**Issue by garrettkatz** [tvraman/emacspeak#20]
I used emacspeak happily on Fedora 20 for some time with (if I recall correctly) emacs 23.4.  Just updated to Fedora 24 and tried installing emacspeak, for which dnf installed emacs 25.1.1 to satisfy the dependency.  Emacs will open but when trying to load emacspeak-setup.el throws the error "widget documentation must be nil or string."  Actually there is a simple fix: in emacspeak-widget.el, I swapped lines 709 and 710, where a keyword argument was being passed to define-widget before a docstring, causing the problem.  Forgive me for not creating a pull request, when I tried re-byte-compiling emacspeak-widget.el, I got more errors that are over my head, so I'll leave that to the experts.  Thanks!

**Comment by tvraman** [comment]
Please look  at the latest version on Github and specify the line number
for that version, I do not see the problem on the line you mention.
--

**Comment by tvraman** [comment]
Found it -- lines had moved a little at GitHub @head. 

Fix checked in.
--

**Comment by tvraman** [comment]
P.S. The fix I checked in for now was to get rid of :help-echo.

That that triggered a problem on Fedora is likely an Emacs bug --
doc-string for define-widget expects the doc string before any keyword arguments.

raman writes:
 > Found it -- lines had moved a little at GitHub @head. 
 > 
 > Fix checked in.
 > -- 

-- 

--

**Comment by garrettkatz** [comment]
Sorry about that, I should have checked the github source to begin with.  I was looking at the code on my local machine which shipped from the Fedora package manager when I installed emacspeak.  In that code, the problem lines were as follows:

(define-widget 'voice 'menu-choice
  :help-echo "Voice selector"
  "Widget for selecting a voice.")

But it looks like even before your latest fix, this problem had already been corrected on github to put the keyword argument after the docstring.  I guess the code version in Fedora's emacspeak package is out of date?  I'll see about taking it up with them.

I appreciate your quick reply!  Best regards,

Garrett

**Comment by tvraman** [comment]
Also, I suspect you hit that error because you likely ran your installed
Emacspeak against the new Emacs 25.1? If yes that is because of the code
having been compiled with the older emacs.

Make sure you cd to <emacspeak> and type  "make clean" and "make" so the
emacspeak lisp code gets recompiled with the new Emacs 25.1
--

**Comment by tvraman** [comment]
closed: Fixed
