### ISSUE TITLE
make install fails on outloud/ALSA

### ISSUE THREAD

**Issue by amerlyq** [tvraman/emacspeak#23]
Exact error text is next:
```make
install: cannot stat 'servers/linux-outloud/ALSA': No such file or directory
```
I conclude it's due to the file `ALSA` was moved into `obsolete` dir.
I think you know better what is right choice to move `ALSA` back from `obsolete` or to remove it from deps.
Current fast fix I used in PKGBUILD on archlinux is to remove that file from install targets at line 145.
Variant using `sed` is next:
```bash
sed -i '/^\${ECI}\/ALSA\s\+/s///' Makefile
```

Also, targets `espeak` and `outloud` aren't built by default, but installed unconditionally.
I suggest to modify `install` target to install files from those targets only if them were built.
Or, which much easier, built both targets by default. 
Possible variant is to create target `all` at the top of makefile with next content:
```make
all: emacspeak espeak outloud
```

**Comment by tvraman** [comment]
closed:
