### ISSUE TITLE
New emacspeak build has no speech synthesis 

### ISSUE THREAD

**Issue by edhofmtx** [tvraman/emacspeak#26]
OS : Debian 9 x64

Steps:
1. Follow build instruction 
2. At the end of make install, there's instruction to add certain line to the top of ~/.emacs file
3. Run emacspeak

Expected Result:
- Emacspeak running with speech synthesis 

Actual Result
- Emacsspeak running without speech synthesis

Debug log:

> Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
>   define-key(nil "" ido-enter-find-file)
>   emacspeak-ido-keys()
>   byte-code("\300 \210\301\302!\207" [emacspeak-ido-keys provide emacspeak-ido] 2)
>   require(emacspeak-ido)
>   (progn (require (quote emacspeak-ido)) (emacspeak-fix-commands-loaded-from "emacspeak-ido") (emacspeak-fix-commands-loaded-from "ido"))
>   (lambda nil (progn (require (quote emacspeak-ido)) (emacspeak-fix-commands-loaded-from "emacspeak-ido") (emacspeak-fix-commands-loaded-from "ido")))()
>   eval-after-load("ido" (progn (require (quote emacspeak-ido)) (emacspeak-fix-commands-loaded-from "emacspeak-ido") (emacspeak-fix-commands-loaded-from "ido")))
>   emacspeak-do-package-setup("ido" emacspeak-ido)
>   byte-code(
>   load("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak.elc")
>   (let ((file-name-handler-alist nil)) (load (expand-file-name "emacspeak.elc" emacspeak-lisp-directory)))
>   eval-buffer(#<buffer  *load*-377568> nil "/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el" nil t)  ; Reading at buffer position 4214
>   load-with-code-conversion("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el" "/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el" nil nil)
>   load("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el" nil nil t)
>   load-file("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el")
>   eval-buffer(#<buffer  *load*> nil "/home/edhoari/.emacs" nil t)  ; Reading at buffer position 77
>   load-with-code-conversion("/home/edhoari/.emacs" "/home/edhoari/.emacs" t t)
>   load("~/.emacs" t t)
>   #[0 "\205\262

Note
- Omit byte code line

**Comment by tvraman** [comment]
Title:    New emacspeak build has no speech synthesis 
Author:   edhofmtx
State:    open
Posted:   Thu 01 Feb 2018 11:21:44 PM PST
Labels:   none

Body
OS : Debian 9 x64

Steps:
1. Follow build instruction
2. At the end of make install, there's instruction to add certain line
   to the top of ~/.emacs file
3. Run emacspeak

Expected Result:
- Emacspeak running with speech synthesis

Actual Result
- Emacsspeak running without speech synthesis


Debug log:

> Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
>   define-key(nil "" ido-enter-find-file) emacspeak-ido-keys()
>   byte-code("\300 \210\301\302!\207" [emacspeak-ido-keys provide
>   emacspeak-ido] 2) require(emacspeak-ido) (progn (require (quote
>   emacspeak-ido)) (emacspeak-fix-commands-loaded-from
>   "emacspeak-ido") (emacspeak-fix-commands-loaded-from "ido"))
>   (lambda nil (progn (require (quote emacspeak-ido))
>   (emacspeak-fix-commands-loaded-from "emacspeak-ido")
>   (emacspeak-fix-commands-loaded-from "ido")))()
>   eval-after-load("ido" (progn (require (quote emacspeak-ido))
>   (emacspeak-fix-commands-loaded-from "emacspeak-ido")
>   (emacspeak-fix-commands-loaded-from "ido")))
>   emacspeak-do-package-setup("ido" emacspeak-ido) byte-code(
>   load("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak.elc")
>   (let ((file-name-handler-alist nil)) (load (expand-file-name
>   "emacspeak.elc" emacspeak-lisp-directory))) eval-buffer(#<buffer
>   *load*-377568> nil
>   "/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el"
>   nil t) ; Reading at buffer position 4214
>   load-with-code-conversion("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el"
>   "/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el"
>   nil nil)
>   load("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el"
>   nil nil t)
>   load-file("/home/edhoari/Downloads/emacspeak-47.0/lisp/emacspeak-setup.el")
>   eval-buffer(#<buffer *load*> nil "/home/edhoari/.emacs" nil t) ;
>   Reading at buffer position 77
>   load-with-code-conversion("/home/edhoari/.emacs"
>   "/home/edhoari/.emacs" t t) load("~/.emacs" t t) #[0 "\205\262

Note
- Omit byte code line

Comments:
There's nothing here!

**Comment by tvraman** [comment]
close: Fixed by updating emacspeak-ido.el
