### ISSUE TITLE
software speech synthesizer clarification?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tvraman/emacspeak#3]
```
the documentation (dated 2001) suggests that the only software speech synth 
supported is IBM's 
ViaVoice.  Is this still the case? and if so are there new links to download 
the ViaVoice speech 
synthesizer?

i have tried installing this on a system with festival and flite installed, but 
cannot even begin to guess 
where to set what backend speech syntheizer it should be using.

```

Original issue reported on code.google.com by `gort.kla...@gmail.com` on 3 May 2009 at 7:08

**Comment by atphalix** [comment]
I don't know about compatibiliy with festival and flite, but on GNU/Linux Espeak software speech synth is fully supported. I installed it under Ubuntu with:
sudo aptitude install emacspeak emacspeak-espeak-server
