### ISSUE TITLE
Uses non-free license for documentation

### ISSUE THREAD

**Issue by sthibaul** [tvraman/emacspeak#31]
Hello,

Debian does not ship the emacspeak documentation because it is not free according to dfsg:

“Permission is granted to make and distribute verbatim copies of this manual without charge provided the copyright notice and this permission notice are preserved on all copies.”

These licensing terms do not permit modifications.

Samuel

**Comment by tvraman** [comment]
Docs are generated from source code, and modifying them separate from
the source is not recommended.

**Comment by sthibaul** [comment]
Err, I can't find where it would be in the source code. For instance, I can't find the announce.texi text anywhere else.

And if it was generated, then instead of setting a non-free licence, a notice should be used to explain that it is a generated doc from the source code and it thus inherits the free licence of the source code.

**Comment by sthibaul** [comment]
(I can't seem to be able to re-open this bug, but it really should be)

**Comment by sthibaul** [comment]
I have to insist: the bug is not fixed: AFAICT, the source code for the documentation is info/*.texi, which are licenced under

"Permission is granted to make and distribute verbatim copies of this manual without charge provided the copyright notice and this permission notice are preserved on all copies.”

which is a non-free licence.
