### ISSUE TITLE
Problem with setup / clarification needed

### ISSUE THREAD

**Issue by ahungry** [tvraman/emacspeak#40]
I want to try this, however even with `emacs -Q /path/to/emacspeak-setup.el`, I run into errors when loading, as follows:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  locate-file-internal

(it seems it can't find a binary it needs? I did attempt to set DTK_PROGRAM to both espeak and espeak-ng (the actual binary I have available))

Should I be ensuring that I start the appropriate server first?  (`/path/to/emacspeak/servers/espeak`)

**Comment by daniel-birket** [comment]
I think that I encountered this just today while helping a user to install emacspeak under MacOS. (I'm a sighted volunteer with some software skills). Noting that it worked in my install from git clone but not his install from tar, I tried making it again from git clone and it worked immediately. Perhaps this is something that was fixed between the release of the tar and the current code?

**Comment by tvraman** [comment]
Likely missing  mplayer binary --- was fixed a while ago. In general
the debug output you submitted was inadequate -- you need to include
the entire backtrace, not just the first line.
