### ISSUE TITLE
Punctuation marks incorrectly pronounced with emacspeak-speak-char?

### ISSUE THREAD

**Issue by tdhock** [tvraman/emacspeak#45]
Hi @tvraman I expected that emacspeak would pronounce this character « as "left guillemet" or "open guillemet" and I do hear that using emacspeak-speak-word and emacspeak-speak-line.
However for that character emacspeak-speak-char says "left hyphen pointing double angle quotation mark" which correctly describes what that punctuation mark looks like, but it is confusing for me (and may be confusing for others who are trying to learn how to correctly pronounce/verbalize punctuation marks). I would rather emacspeak just use the "left guillemet" here as well. Is that possible/configurable?

**Comment by tvraman** [comment]
same as the previous issue, see response there

**Comment by tdhock** [comment]
hi thanks for the ref to #46 which mentions that emacspeak gets the descriptions such as "left guillemet" from unicode tables, but I don't see how that helps with this issue. Can you please clarify?

In what ways are punctuation marks treated differently by emacspeak-speak-char and emacspeak-speak-word? 

I would like to run emacspeak-speak-char after every keypress, to speak every character as it is inserted, as is the default emacspeak behavior. However I would like it to speak those punctuation in the way that emacspeak-speak-word does, e.g. "left guillemet" instead of "left hyphen pointing double angle quotation mark" -- can you please clarify how to do that?
