### ISSUE TITLE
configurable foreign language punctuation?

### ISSUE THREAD

**Issue by tdhock** [tvraman/emacspeak#46]
Hi @tvraman I have found that emacspeak-speak-word does a great job at speaking punctuation marks in French after doing (dtk-set-language fr).

For example the character / is spoken as "barre oblique" and ( is spoken as "parenthèse gauche" which is great.

However the character \ is spoken as "backslash" which is English. Is there any way to configure a French version, for example "Barre oblique inversée" ?

There are several others I would like to configure/change, for example [ is "left bracket" but should be "crochet gauche" 

I tried searching the source code for these words, which I thought may lead to some configuration variables, but I did not find anything, so I am asking here.

Thanks in advance for any help/advice.

**Comment by tvraman** [comment]
Emacspeak gets char names from the unicode table.
It also has extension points for pronunciations in module
dtk-unicode.el study the code there.

**Comment by tdhock** [comment]
I looked at dtk-unicode.el and I only see a few defcustom items. The most relevant seems to be dtk-unicode-character-replacement-alist and I tried adding the following item to that alist:
```
(91 . "crochet gauche")
```
but I don't hear any change after that, even after restarting emacspeak.

I also don't see any mention of language, so can you please explain how I could get emacspeak to do language-specific customization? For example the character [ would be "left bracket" by default in English, and then "crochet gauche" after having done (dtk-set-language fr).

**Comment by tvraman** [comment]
this is not lang specific, it's character-set specific 
--
