### ISSUE TITLE
emacspeak-handle-action-at-point is void with EVIL

### ISSUE THREAD

**Issue by TiFaBl** [tvraman/emacspeak#47]
First of all: thank you very much for the amazing work with this package! I am not an experienced emacs user and tried to debug this as far as possible. If i missed anything, i am happy to provide further information.

### Problem description
emacspeak-handle-action-at-point appears to not be loaded correctly which results in errors when using commands hooked to it.

### System
Ubuntu 20.04.1
This is GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20
Discovered with Emacspeak 52.0,   WorkAtHomeDog 2e5568e0e
also just tryed with Emacspeak 52.0,   WorkAtHomeDog c200d64

### Steps to reproduce
Run `emacs -q -l /path/to/emacspeak/lisp/emacspeak-setup.el
`
then load/eval 
```
(require 'package)
(package-initialize)
(require 'use-package)

;; EVIL
(use-package evil
  :ensure t
  :config
  (evil-mode 1))
```

Hit dd, to delete a line.

### Debug stack trace

```
Debugger entered--Lisp error: (void-function emacspeak-handle-action-at-point)
  emacspeak-handle-action-at-point()
  emacspeak-speak-region(83 84)
  ad-Advice-evil-delete(#f(compiled-function (beg end &optional type register yank-handler) "Delete text from BEG to END with TYPE.\nSave in REGISTER or in the kill-ring with YANK-HANDLER." (interactive #f(compiled-function () #<bytecode 0x157f099c4065>)) #<bytecode 0x157f0991ecf1>) 83 84 line nil nil)
  apply(ad-Advice-evil-delete #f(compiled-function (beg end &optional type register yank-handler) "Delete text from BEG to END with TYPE.\nSave in REGISTER or in the kill-ring with YANK-HANDLER." (interactive #f(compiled-function () #<bytecode 0x157f09931e19>)) #<bytecode 0x157f0991ecf1>) (83 84 line nil nil))
  evil-delete(83 84 line nil nil)
  #<subr funcall-interactively>(evil-delete 83 84 line nil nil)
  apply(#<subr funcall-interactively> evil-delete (83 84 line nil nil))
  ad-Advice-funcall-interactively(#<subr funcall-interactively> evil-delete 83 84 line nil nil)
  apply(ad-Advice-funcall-interactively #<subr funcall-interactively> (evil-delete 83 84 line nil nil))
  funcall-interactively(evil-delete 83 84 line nil nil)
  #<subr call-interactively>(evil-delete nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> evil-delete nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (evil-delete nil nil))
  #f(advice-wrapper :around #<subr call-interactively> ad-Advice-call-interactively)(evil-delete nil nil)
  apply(#f(advice-wrapper :around #<subr call-interactively> ad-Advice-call-interactively) evil-delete (nil nil))
  call-interactively@ido-cr+-record-current-command(#f(advice-wrapper :around #<subr call-interactively> ad-Advice-call-interactively) evil-delete nil nil)
  apply(call-interactively@ido-cr+-record-current-command #f(advice-wrapper :around #<subr call-interactively> ad-Advice-call-interactively) (evil-delete nil nil))
  call-interactively(evil-delete nil nil)
  command-execute(evil-delete)

```
### Solution hint
When i manually load/eval emacspeak/lisp/emacspeak-wizards.el the emacspeak-handle-action-at-point gets reassigned. Using C-h f to describe emacspeak-handle-action-at-point also gets it working. I think there is some loading issue.

**Comment by didiercolle** [comment]
I believe commit 71c1b8b (dated Sep 24th) is the guilty one.
@TiFaBl can you confirm this that the issue you have is there for that commit  71c1b8b but not in the commit before ( commit 23463939d )?

**Comment by tvraman** [comment]
Thanks for reporting this.
I suspect you may not have done a full build, ie make clean; make
config; make or make q for short.
This is needed when code moves around.

For the record, I've moved the action code back to module
emacspeak-speak from the emacspeak-wizards module for other reasons.

Let me know if you are still seeing the issue after updating from git
and doing a clean build as described above.

**Comment by didiercolle** [comment]
I just tried following command: git pull origin && git clean -fdx && make clean && make config && make && make espeak ; espeak DONE (and then silenced my shell output with M-x dtk-toggle-quiet) 
afterwards, restarted emacs. 

result: indeed, issue seems to be gone now. 
(fyi: in last days I have been updating my system from an pretty old version (a year or older if I remember well), and found out that a make clean still left some untracked files/dirs in the output of a git status cmd... therefore, I replaced the make clean with a git clean -fdx that seemed to be more thorough....) 


Van: "T. V. Raman" <notifications@github.com> 
Aan: "tvraman/emacspeak" <emacspeak@noreply.github.com> 
Cc: "didier" <didier.colle@telenet.be>, "Comment" <comment@noreply.github.com> 
Verzonden: Woensdag 14 oktober 2020 20:31:13 
Onderwerp: Re: [tvraman/emacspeak] emacspeak-handle-action-at-point is void with EVIL (#47) 





Thanks for reporting this. 
I suspect you may not have done a full build, ie make clean; make 
config; make or make q for short. 
This is needed when code moves around. 

For the record, I've moved the action code back to module 
emacspeak-speak from the emacspeak-wizards module for other reasons. 

Let me know if you are still seeing the issue after updating from git 
and doing a clean build as described above.

**Comment by tvraman** [comment]
glad it works, will close the issue.
-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Fixed by clean build. Closing issue.

**Comment by TiFaBl** [comment]
thanks for your efforts, I also just did some testing and can second @didiercolle.
Using the full command and therefore also cleaning the untraced files fixed the issue for me as well (even though i am currently using emacs kbd instead of evil).

Not sure if that is of any use but without the git clean it did not work for me on the following version:
commit 558cbdf0fdde75e55e86b96e123958e76d41ccbf (HEAD -> master, origin/master, origin/HEAD)
Author: T.V Raman <tv.raman.tv@gmail.com>
Date:   Sat Oct 3 10:28:15 2020 -0700
