### ISSUE TITLE
comint results in "error in process filter: Wrong type argument: stringp, nil"

### ISSUE THREAD

**Issue by didiercolle** [tvraman/emacspeak#48]
cfr. my comment on commit 3371935
fyi: the clean build trick as in issue #47 did not work for this issue....

I guess this issue also makes it impossible for me to open a file with sudo via tramp (C-x C-f /sudo::/...)

Commenting out emacspeak related code in my .emacs file and restarting emacs seems to avoid these problems.

this is a critical issue for me.

emacs version: 27.1

**Comment by tvraman** [comment]
Cannot debug without a backtrace.

**Comment by tvraman** [comment]
P.S. I just tried 
C-, f runs the command emacspeak-wizards-find-file-as-root
and it does not throw any errors.

If you are still able to reproduce this error, I'll need a backtrace
as requested earlier.

**Comment by didiercolle** [comment]
backtrace when doing a "sudo ls" in a shell buffer: 
> (wrong-type-argument stringp nil) 
> call-process(nil nil 0 nil "/home/dcolle/src/emacspeak/sounds/prompts/pwd.mp3") 
> emacspeak-prompt("pwd") 
> ad-Advice-read-passwd(#f(compiled-function (prompt &optional confirm default) "Read a password, prompting with PROMPT, and return it.\nIf optional CONFIRM is non-nil, read the password twice to make sure.\nOptional DEFAULT is a default password to use instead of empty input.\n\nThis function echoes `*' for each character that the user types.\nYou could let-bind `read-hide-char' to another hiding character, though.\n\nOnce the caller uses the password, it can erase the password\nby doing (clear-string STRING)." #<bytecode 0x1fdd7fbfc9b9>) "Password: ") 
> apply(ad-Advice-read-passwd #f(compiled-function (prompt &optional confirm default) "Read a password, prompting with PROMPT, and return it.\nIf optional CONFIRM is non-nil, read the password twice to make sure.\nOptional DEFAULT is a default password to use instead of empty input.\n\nThis function echoes `*' for each character that the user types.\nYou could let-bind `read-hide-char' to another hiding character, though.\n\nOnce the caller uses the password, it can erase the password\nby doing (clear-string STRING)." #<bytecode 0x1fdd7fbfc9b9>) "Password: ") 
> read-passwd("Password: ") 
> comint-send-invisible("Password: ") 
> comint-watch-for-password-prompt("Password: ") 
> run-hook-with-args(comint-watch-for-password-prompt "Password: ") 
> #f(compiled-function (process string) #<bytecode 0x156b3451b0f1>)(#<process shell> "Password: ") 
> ad-Advice-comint-output-filter(#f(compiled-function (process string) #<bytecode 0x156b3451b0f1>) #<process shell> "Password: ") 
> apply(ad-Advice-comint-output-filter #f(compiled-function (process string) #<bytecode 0x156b3451b0f1>) (#<process shell> "Password: ")) 
> comint-output-filter(#<process shell> "Password: ") 



Van: "T. V. Raman" <notifications@github.com> 
Aan: "tvraman/emacspeak" <emacspeak@noreply.github.com> 
Cc: "didier" <didier.colle@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Donderdag 15 oktober 2020 01:34:34 
Onderwerp: Re: [tvraman/emacspeak] comint results in "error in process filter: Wrong type argument: stringp, nil" (#48) 





Cannot debug without a backtrace.

**Comment by didiercolle** [comment]
I did not know about the C-, f cmd... I do not understand its behavior (it cannot open files outside current dir? it cannot create new files as you can with C-x C-f?), but it indeed at first view seems not to raise any error, although I am not sure whether I went up in the process to the phase where a password prompt is expected, given I did not know about the cmd. 

backtrace after C-x C-f /sudo::/e TAB 

(wrong-type-argument "stringp nil") 
signal(wrong-type-argument ("stringp nil")) 
tramp-signal-hook-function(wrong-type-argument ("stringp nil")) 
signal(wrong-type-argument ("stringp nil")) 
tramp-maybe-open-connection((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/bin" nil)) 
tramp-send-command((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/bin" nil) "test 0 2>/dev/null; echo tramp_exit_status $?") 
tramp-send-command-and-check((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/bin" nil) "test 0") 
tramp-get-test-command((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/bin" nil)) 
tramp-run-test("-d" #("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
tramp-sh-handle-file-directory-p(#("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
apply(tramp-sh-handle-file-directory-p #("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
tramp-sh-file-name-handler(file-directory-p #("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
apply(tramp-sh-file-name-handler file-directory-p #("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
tramp-file-name-handler(file-directory-p #("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
file-directory-p(#("/sudo:root@localhost:/bin" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
#f(compiled-function (x) #<bytecode 0x156b34819489>)("/bin") 
mapcar(#f(compiled-function (x) #<bytecode 0x156b34819489>) ("/bin" "/usr/bin" nil nil "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin" "/local/bin" "/local/freeware/bin" "/local/gnu/bin" "/usr/freeware/bin" "/usr/pkg/bin" "/usr/contrib/bin" "/opt/bin" "/opt/sbin" "/opt/local/bin")) 
tramp-get-remote-path((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/" nil)) 
tramp-get-remote-perl((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("localhost" 0 9 (tramp-default t)) nil "/" nil)) 
tramp-sh-handle-file-name-all-completions("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
apply(tramp-sh-handle-file-name-all-completions ("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)))) 
tramp-sh-file-name-handler(file-name-all-completions "e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
apply(tramp-sh-file-name-handler file-name-all-completions ("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)))) 
tramp-file-name-handler(file-name-all-completions "e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
file-name-all-completions("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t))) 
tramp-handle-file-name-completion("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p) 
apply(tramp-handle-file-name-completion ("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p)) 
tramp-sh-file-name-handler(file-name-completion "e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p) 
apply(tramp-sh-file-name-handler file-name-completion ("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p)) 
tramp-file-name-handler(file-name-completion "e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p) 
file-name-completion("e" #("/sudo:root@localhost:/" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p) 
completion-file-name-table(#("/sudo:root@localhost:/e" 6 10 (tramp-default t) 11 20 (tramp-default t)) file-exists-p nil) 
try-completion(#("/sudo:root@localhost:/e" 6 10 (tramp-default t) 11 20 (tramp-default t)) completion-file-name-table file-exists-p) 
completion-basic-try-completion(#("/sudo:root@localhost:/e" 6 10 (tramp-default t) 11 20 (tramp-default t)) completion-file-name-table file-exists-p 23) 
#f(compiled-function (style) #<bytecode 0x156b34618381>)(basic) 
completion--some(#f(compiled-function (style) #<bytecode 0x156b34618381>) (basic partial-completion emacs22)) 
completion--nth-completion(1 "~//sudo::/e" read-file-name-internal file-exists-p 11 (metadata (category . file) (completion--unquote-requote . t))) 
completion-try-completion("~//sudo::/e" read-file-name-internal file-exists-p 11 (metadata (category . file) (completion--unquote-requote . t))) 
completion--do-completion(12 23) 
completion--in-region-1(12 23) 
#f(compiled-function (start end collection predicate) #<bytecode 0x1fdd7fbf2d65>)(12 23 read-file-name-internal file-exists-p) 
apply(#f(compiled-function (start end collection predicate) #<bytecode 0x1fdd7fbf2d65>) (12 23 read-file-name-internal file-exists-p)) 
#f(compiled-function (funs global args) #<bytecode 0x1fdd7a0be5a1>)(nil nil (12 23 read-file-name-internal file-exists-p)) 
completion--in-region(12 23 read-file-name-internal file-exists-p) 
completion-in-region(12 23 read-file-name-internal file-exists-p) 
#f(compiled-function () (interactive nil) #<bytecode 0x1fdd7fc04721>)() 
ad-Advice-minibuffer-complete(#f(compiled-function () (interactive nil) #<bytecode 0x1fdd7fc04721>)) 
apply(ad-Advice-minibuffer-complete #f(compiled-function () (interactive nil) #<bytecode 0x1fdd7fc04721>) nil) 
minibuffer-complete() 
#<subr funcall-interactively>(minibuffer-complete) 
apply(#<subr funcall-interactively> minibuffer-complete nil) 
ad-Advice-funcall-interactively(#<subr funcall-interactively> minibuffer-complete) 
apply(ad-Advice-funcall-interactively #<subr funcall-interactively> minibuffer-complete) 
funcall-interactively(minibuffer-complete) 
#<subr call-interactively>(minibuffer-complete nil nil) 
ad-Advice-call-interactively(#<subr call-interactively> minibuffer-complete nil nil) 
apply(ad-Advice-call-interactively #<subr call-interactively> (minibuffer-complete nil nil)) 
call-interactively(minibuffer-complete nil nil) 
command-execute(minibuffer-complete) 
read-from-minibuffer("Find file: " "~/" (keymap (keymap (32)) keymap (10 . minibuffer-complete-and-exit) (13 . minibuffer-complete-and-exit) keymap (15 . switch-to-completions) (67108896 . emacspeak-minibuffer-choose-completion) (0 . emacspeak-minibuffer-choose-completion) (16 . emacspeak-minibuffer-previous-completion) (14 . emacspeak-minibuffer-next-completion) (menu-bar keymap (minibuf "Minibuf" keymap (tab menu-item "Complete" minibuffer-complete :help "Complete as far as possible") (space menu-item "Complete Word" minibuffer-complete-word :help "Complete at most one word") (63 menu-item "List Completions" minibuffer-completion-help :help "Display all possible completions") "Minibuf")) (27 keymap (118 . switch-to-completions)) (prior . switch-to-completions) (63 . minibuffer-completion-help) (32 . minibuffer-complete-word) (9 . minibuffer-complete) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the min...") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuf...") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\15" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . abort-recursive-edit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (60 . minibuffer-beginning-of-buffer) (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil file-name-history "~/" nil) 
completing-read-default("Find file: " read-file-name-internal file-exists-p confirm-after-completion "~/" file-name-history "~/" nil) 
completing-read("Find file: " read-file-name-internal file-exists-p confirm-after-completion "~/" file-name-history "~/") 
read-file-name-default("Find file: " nil "/home/dcolle/" confirm-after-completion nil nil) 
read-file-name("Find file: " nil "/home/dcolle/" confirm-after-completion) 
find-file-read-args("Find file: " confirm-after-completion) 
byte-code("\300\301\302 \"\207" [find-file-read-args "Find file: " confirm-nonexistent-file-or-buffer] 3) 
#<subr call-interactively>(find-file nil nil) 
ad-Advice-call-interactively(#<subr call-interactively> find-file nil nil) 
apply(ad-Advice-call-interactively #<subr call-interactively> (find-file nil nil)) 
call-interactively(find-file nil nil) 
command-execute(find-file) 




Van: "T. V. Raman" <notifications@github.com> 
Aan: "tvraman/emacspeak" <emacspeak@noreply.github.com> 
Cc: "didier" <didier.colle@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Donderdag 15 oktober 2020 01:42:47 
Onderwerp: Re: [tvraman/emacspeak] comint results in "error in process filter: Wrong type argument: stringp, nil" (#48) 





P.S. I just tried 
C-, f runs the command emacspeak-wizards-find-file-as-root 
and it does not throw any errors. 

If you are still able to reproduce this error, I'll need a backtrace 
as requested earlier.

**Comment by tvraman** [comment]
check to see why your emacspeak-m-player-program is set to nil --- it
should be the path to mplayer.

**Comment by TiFaBl** [comment]
i actually had this "problem" as well and the solution was to install mplayer, which additionally gave me the amazing sound effects that i was not aware of before 👍 
At some point, the dependency to mplayer must have been established. Maybe a short notice in the install instructions would be helpful, if it is not just us who missed it beeing stated somewhere.

**Comment by tvraman** [comment]
Do you have suggestions as to where you would have looked to find out
about mplayer?

It's hard to tell where it makes sense to document the requirement
with respect to users finding it.

For the record, I've notw make emacspeak-prompt to check for mplayer
rather than erroring out, but that also means that the next user who
doesn't have mplayer will silently miss out on discovering its
goodness. and  now that you have mplayer, check out module
emacspeak-m-player which provides  a ton of media player goodness.

**Comment by TiFaBl** [comment]
T. V. Raman writes:

> Do you have suggestions as to where you would have looked to find out
> about mplayer?
>
> It's hard to tell where it makes sense to document the requirement
> with respect to users finding it.
>
I remember that i checked the install instructions first
(http://tvraman.github.io/emacspeak/manual/Installation.html#Installation)
and did that now again to see if i missed something. Not sure if it
would be worth an own section, e.g. 5.2 Requirements.

I also looked at 7 The Emacspeak Audio Desktop but wasn't really
expecting it there, since object refers to the emacs internals.

> For the record, I've notw make emacspeak-prompt to check for mplayer
> rather than erroring out, but that also means that the next user who
> doesn't have mplayer will silently miss out on discovering its
> goodness. and  now that you have mplayer, check out module
> emacspeak-m-player which provides  a ton of media player goodness.

I really liked the additional feedbacks that i discovered and have a
todo to move my radio streams and other media to emacs and use the
emacspeak-m-player now. Thanks a lot!

**Comment by tvraman** [comment]
So the bigger picture here is that Emacspeak is designed to leverage all
things available on Linux --- and starting to document everything that
should be installed goes beyond the scope of emacspeak's documentation,
and if written wouldn't get read by most users anyway.

Since you ask, and appear enthusiastic to learn and leverage the system,
here are a few other Linux things you may want -- this is not an
exhaustive list

1. mplayer for media and radio
   2. sox for sound effects
      3. boodler for soundscapes
         4. xsltproc for filtering Web sites intelligently eg Google
            Search etc
            5. ladspa filters for more sound effects
               6. Units for unit conversion

                  and a lot, lot more.

                  One good way to learn these and to discover them is to
                  look at the Emacspeak blog -- you'll serendipitously
                  discover things. Note that the blog-archive is
                  available locally if you have done  a git checkout.

                  Enjoy,

                  --Raman 
-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮
