### ISSUE TITLE
Language switching on MacOS

### ISSUE THREAD

**Issue by suky57** [tvraman/emacspeak#49]
Conditions:
- OS: MacOS 10.14
- Emacs: v27
- Emacspeak: v52.0
- System language: Czech
- System voice: Czech
- LC_ALL=cs_CZ.UTF-8 encoding

My whole system locales are set for UTF-8. Once I choose the czech TTS voice (using "mac" speech server with emacspeak) it still pronounces the national characters as well as punctuations in english.

Is there any way how to force Emacspeak to use also the czech language instead of English?

Curious is that if I  run
./servers/mac
% q "some text including czech characters"
% d

it reads it correctly but within the emacs, everything is being read in enblish by czech voice

**Comment by tvraman** [comment]
1. I dont use MacOS, nor do I use Czech, so you'll need to go further
   yourself to debug this. Note that Emacspeak  does not support
   multiple languages out of the box. For starters, look at
   dtk-unicode.el and perhaps some of the char replacement tables in
   the dtk-*.el modules.
