### ISSUE TITLE
updating the FSF addresses in the file headers

### ISSUE THREAD

**Issue by juhp** [tvraman/emacspeak#52]
There are many references to the old FSF address in the file headers, particularly `lisp/*.el`.

The current FSF address is "51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."

ie the text:

```
;;; You should have received a copy of the GNU General Public License
;;; along with GNU Emacs; see the file COPYING.  If not, write to
;;; the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
```
should be updated to reflect the current address https://www.fsf.org/about/contact/.

I can probably come up with PR for this later if you would prefer that.

It would also be better to include a copy of the GPL `COPYING` license file.

**Comment by tvraman** [comment]
I'll fix the address first. Thanks for the heads-up

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
