### ISSUE TITLE
support for pipewire?

### ISSUE THREAD

**Issue by juhp** [tvraman/emacspeak#53]
Does anyone have emacspeak working under Linux pipewire audio?

Fedora 34 uses pipewire instead of pulseaudio to manage sound and I haven't been able to get emacspeak audio working with it yet.

**Comment by tvraman** [comment]
Jens Petersen ***@***.***> writes:

Emacspeak does not use pulseaudio -- the outloud server uses alsa calls,
and espeak at some level uses portaudio.

So the problem with pipewire is likely elsewhere
> Does anyone have emacspeak working under Linux pipewire audio?
>
> Fedora 34 uses pipewire instead of pulseaudio to manage sound and I
> haven't been able to get emacspeak audio working with it yet.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by juhp** [comment]
Okay then I need to look into portaudio perhaps: the thing is espeak from the commandline works,
but there is no interactive output coming from emacspeak in this case.

**Comment by tvraman** [comment]
You need to build and debug the emacspeak speech server from the shell.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
For anyone who has a system with pipewire,  please check if:

1. Your distribution provides a pipewire-alsa package (my own setup
   --- Debian --- does not).
   2. If you have pipewire-alsa available (arch linux has it) then
      install pipewire-alsa and see if the emacspeak speech servers
      work.
      
      3. Separately, you might be  get the TTS servers working with
         pipewire if you remove your .asoundrc  --- assuming you have
         one set up.

**Comment by tvraman** [comment]
See this
https://mail.emacspeak.org/hyperkitty/list/emacspeak@emacspeak.org/thread/7I5AWOQ4OWVVCOB5XLB6OTKCNH5ZUFI7/
message on the Emacspeak Mailing List Archive for more details.

**Comment by juhp** [comment]
Thank you - going to test this later.
Fedora seems to install pipewire-alsa by default AFAICT

**Comment by tvraman** [comment]
Jens Petersen ***@***.***> writes:


thanks -- let   folks know via the emacspeak list as to what you
discover.

If pipewire-alsa does fix it, we might need to file a bug upstream
against distros like Debian and Fedora that presently dont include
pipewire-alsa

> Thank you - going to test this later.
> Fedora seems to install pipewire-alsa by default AFAICT
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
