### ISSUE TITLE
MacOS: mac/server script uses system Python

### ISSUE THREAD

**Issue by rbistolfi** [tvraman/emacspeak#68]
The `mac/server` script shebang line points to the system Python installation. This makes using a virtualenv for managing emacspeak dependencies a bit harder. I think using `#! /usr/bin/env python` would honor `$PATH` and use the binary provided by the active virtualenv instead.

Thanks for considering our issue.
Regards,

Rodrigo

**Comment by robertmeta** [comment]
Is there any downside to this approach?  I can't think of one, I will go ahead and see if they will accept a PR with this change.

**Comment by robertmeta** [comment]
@tvraman this issue can be closed
