### ISSUE TITLE
light.el conflicts with ultratex

### ISSUE THREAD

**Issue by tarsius** [tvraman/emacspeak#73]
The ultratex package also contains a library named `light`. According to the library header it was created in 2005 and it was checked into git in 2012. Could you please rename your `light`?

**Comment by tvraman** [comment]
No.
I doubt there are emacspeak users who use that other package and I dont
have the cycles to do this form of busy work, Sorry

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
Okay.

**Comment by tvraman** [comment]
P.S. Apologies for the tone of my message, it came across as harsh which
was not my intent.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
No problem. As a maintainer I do understand that sometimes all these requests, which in the grand scheme of things aren't that important, can be a bit much and sometimes lead to, let's say, concise responses.
