### ISSUE TITLE
Pulse sync tts write error after launching emacs with emacspeak on Slint

### ISSUE THREAD

**Issue by sevapopov2** [tvraman/emacspeak#75]
Hello,
I compiled Emacspeak on Slint.
Slint is a distro slackware made accessible for blind people.
You can [find more here](http://slint.fr)
I could compile Emacspeak from source with make config and make commands and build native espeak server by going to servers directory.
Then I created the .emacs file at ~/.emacs and typed the command provided after the compilation.
After I launch emacs I hear eSpeak says espeak 1.51-dev but espeakup in console tells that there is an error in function pulse sync tts write, something like that.
Unfortunately I am not able to copy it but this is how it sounds.
When I press up/down arrows eSpeak tells nothing in emacspeak and different commands like ctrl+e tab don't make it speaking.
I will note that I could compile emacspeak only in console, the compilation process didn't work in GUI.
How can I make it working? I am curious to look what emacspeak actually is.
Thank you!

**Comment by robertmeta** [comment]
As you mentioned, slint is a distro focused on accessibility.  Therefore it actually comes with a ready to rock copy of emacs with emacspeaks.  I would start with thier version and then try more advanced stuff...

Do something like ```mv ~/.emacs.d ~/.emacs.bak``` then just run ```switch-on emacspeak``` and you should instantly have a functional, if a bit out of date copy of emacspeaks.

**Comment by robertmeta** [comment]
I haven't tried it yet, but I have read good things about http://www.cocofrix.com/
