### ISSUE TITLE
Emacspeaks breaks company-mode

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#76]
Company mode works fine with emacspeak turned off, when I turn it on completions stop working and I get no completions in the scratch buffer.

```
Company: An error occurred in auto-begin
Wrong type argument: stringp, nil
```

M-x: company-diag 

```
Emacs 28.2 (aarch64-apple-darwin21.6.0) of 2022-09-14 on admins-Virtual-Machine.local
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: messages-buffer-mode
Prefix: ""
Completions:
  "ring"
  "kill"
  "copied"
  "lines"
  "containing"
  "region"
  "mark"
  "messages"
  "buffer"
  "only"
  "read"
  "buffer"
  "times"
  "mark"
  "stringp"
  "argument"
  "type"
  "wrong"
  "begin"
  "auto"
  "occurred"
  "error"
  "company"
  "buffer"
  "current"
  "enabled"
  "mode"
  "company"
  "buffer"
  "current"
  "disabled"
  "mode"
  "company"
  "times"
  "done"
  "advice"
  "emacspeak"
  "loading"
  "deprecated"
  "package"
  "type"
  "system"
  "emacs"
  "about"
  "information"
  "done"
  "mode"
  "revert"
  "auto"
  "magit"
  "turning"
  "done"
  "source"
  "custom"
  "emacs"
  "emacs"
  "rmelton"
  "users"
  "loading"
  "done"
  "source"
  "local"
  "init"
  "emacs"
  "rmelton"
  "users"
  "loading"
  "perfectly"
  "functioning"
  "circuits"
  "operational"
  "completely"
  "agiledog"
  "emacspeak"
  "overview"
  "press"
  "done"
  "source"
  "loaddefs"
  "emacspeak"
  "loading"
  "done"
  "refresh"
  "package"
  "elpa"
  "host"
  "contacting"
```

----

New to emacs (came for emacspeak) so let me know what if anything I can do to help debug.

**Comment by tvraman** [comment]
Works fine in my set up.

Turn on debug: M-x toggle-debug-on-error and take a look at what the
gacktrace says -- and also specify:

1. Version of Emacspeak
2. What language mode the error triggers in,
3. And any company related custom settings you have on.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
When answering question 1, I realized I am on 56, not 57, let me upgrade before doing anything else.

**Comment by robertmeta** [comment]
Going to close this -- as 57 created entirely new problems.

**Comment by tvraman** [comment]
Thanks. Though nothing changed in 57 re company from memory.

From the message you sent, it looks like dabbrev is  what triggered your
 error; please send a backtrace along with what exactly you typed when
 it triggered 


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
Yep, if this reoccurs once I fix other issues in 67, I will reopen a bug with all the details in it.

**Comment by robertmeta** [comment]
In case anyone else has this issue, it was due to missing sox.  On mac, fixed by just ```brew install sox```
