### ISSUE TITLE
Can you independantly alter sound effects volume? 

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#78]
After installing sox, I have a brand new world of delightful sound effects!  But, they are a little loud versus the speaking volume, can I adjust this somehow?

**Comment by tvraman** [comment]
Robert Melton ***@***.***> writes:


That's likely best done by:

1. cd to sounds/<theme> for the theme you're using;
2. you can adjust the gain of a file by using sox (do this once)
sox old.wav new.wav gain <gain>
Figure out the gain you like by using 
play file.wav gain <gain>

If running this under a git checkout, create a new branch for yourself
(local branch) and do the change there so things dont get over-written
when you do a git pull in the future 

> After installing sox, I have a brand new world of delightful sound effects! But, they are a little loud versus the
> speaking volume, can I adjust this somehow?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
Sweet, thanks again @tvraman
