### ISSUE TITLE
Extremely Slow Speaking (on master using mac)

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#81]
When testing master for my PR (#80) I noticed on that server/mac was speaking extremely slowly and ignoring my settings ... I traced it down to a specific commit, but I am not yet proficient enough to fix it. 

[The Commit](https://github.com/tvraman/emacspeak/commit/0b24b848fdd0113be532e2af326085cfe42eeb46)

**Comment by tvraman** [comment]
specify which commit 

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
0b24b848f

**Comment by tvraman** [comment]
Good catch.

tts_sync_state  now takes one additional flag 
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
should be fixed now (untested), pull and test.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
Yep, that fixed it, closing this.
