### ISSUE TITLE
Deadgrep doesn't read filenames on file-skip (M-n M-p)

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#82]
Mostly explained in the subject, but deadgrep lets you skip between files with M-n and M-p and individual matches with n and p.  When skipping around with M-n M-p the filenames are not read aloud. 

As an aside, is rg.el more well supported?  I saw both were in things emacspeaks tries to support.

**Comment by tvraman** [comment]
I use both. 

Suspect not all commands are speech-enabled -- or some commands may have
been added later by deadgrep.

See emacspeak-deadgrep to learn how these are done -- that said M-n and
M-p as you'll see likely take a couple of lines of code to
speech-enable.




-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
