### ISSUE TITLE
macOS speech server extremely buggy on Ventura.

### ISSUE THREAD

**Issue by TheQuinbox** [tvraman/emacspeak#84]
On macOS 13 (Ventura), Emacspeak is extremely buggy. When launching Emacspeak, I hear the intro sound, but it pauses about half way through, normally when saying emacspeak. So its, This, is emacsp... about 1 second pause, peak.
That's not all, though. When going through even just the Emacs tutorial, it will stop reading randomly, with seemingly no way to bring it back. I'm fairly new to Emacs though, so perhaps there's a way to recover it, but only certain sounds will play during this time, too (e.g. the confirm sound when wanting to quit and relaunch).
Also, I'm not entirely sure this one is related, but its happened 3 times with Emacspeak running and 0 without, so I have to assume so. My audio will sometimes get really, really crackly, progressively getting worse and worse until my headphones are letting out this absolutely awful combination of white noise and high frequencies. Unplugging my headphones makes it stop, but plugging them back in results in it happening again.
If there's anything I can provide to help debug these issues, please let me know. Emacs seems awesome, and I really want to learn it, but my mac is the only machine I can run it on, and these issues render it basically unusable.

**Comment by TheQuinbox** [comment]
CC @Robertmeta, as you seem to be one of the main people doing things with the macOS side of things.

**Comment by devinprater** [comment]
The only time I get the sound issues is if I have my MacBook (Intel, late
2019 model Pro with 4 thunderbolt ports) plugged into an external display.
With the first issue when Emacspeak starts up, it does that. It pauses,
then resumes as more parts of Emacs loads. I don't have the second issue,
but make sure you have stuff like sox and MPG123 and such, and Mplayer too.
Devin Prater
***@***.***

**Comment by TheQuinbox** [comment]
I'm on an M1 MacBook Air, with nothing connected other than a pare of wired headphones when it happens. I did brew install mplayer before ever running Emacspeak, and think I have Sox and mpg123 (my Edbrowse config references them and I can play files).

**Comment by devinprater** [comment]
Oh, which voice are you using?
Devin Prater
***@***.***

Https://devinprater.micro.blog

**Comment by TheQuinbox** [comment]
I'm using Alex, haven't really tried with any others.

**Comment by TheQuinbox** [comment]
Just got it to happen again, although I have literally no idea how. That is, I totally lost speech, and had to quit Emacs and relaunch it to get it back. I was just pressing control N through the Emacs tutorial, and boom. No warning, just, gone. Emacspeak itself isn't crashing though, I still got a sound when quitting, telling me that I was at a prompt.

**Comment by TheQuinbox** [comment]
Oh, now this is even more interesting. Previously, I was using Emacs-mac, when I was having all of these issues. I'm now using emacs-plus, and it seems much faster (for example, there's no pause when the this is Emacspeak message plays). However, literally nothing reads. Both to Emacspeak or VoiceOver. I just get pure and utter silence when arrowing, unless I hit an edge, in which case I get an error noise.

**Comment by robertmeta** [comment]
First of all, Emacs-mac is completely unusable with Emacspeaks.  Emacs Plus is what I use and recommend. 

Secondly, if you are getting no voice, it is very likely the mac server isn't loading properly, I recommend you try running it from the terminal and make sure you get no errors.  Additionally make sure you got Python 3 installed.  No voice at all is just a server not starting issue and hopefully straight-forward to fix (5 days later, hopefully you got it working). 

As for the "stuff getting weird" the crackles and so forth, this is an issue I am actively tracking down (thank you for the post, I thought it was just me).  It takes longer to happen with Emacs Plus but can still happen.  Generally it takes days for me to see this bug and I think it is something in the sox stuff in the mac server.

**Comment by devinprater** [comment]
Someone said it might be an issue with one of Rogue Amoeba’s system extensions. I notice it when I have my Mac plugged into a docking station with an external monitor attached.
Devin Prater
***@***.***

Https://devinprater.micro.blog

**Comment by robertmeta** [comment]
@devinprater I use a different app -- but similar snatching of audio --- so that could well be it.  I use Cleanshot X which has a (beta) driver to capture audio from desktop during recording... I can disable it and see if it goes away.  

Will report back soon.

**Comment by TheQuinbox** [comment]
Hi, when I say I don't get speech, its fairly random when it happens. Sometimes it happens when I first launch Emacs-plus, but it eventually recovers. But then it'll just randomly die again. Is there a way for me to capture the stdout of the speech server while Emacs is running?

**Comment by devinprater** [comment]
Isn't there a Mac-log speech server?
Devin Prater
***@***.***

**Comment by robertmeta** [comment]
So, I removed the custom audio acapture driver from Cleanshot X and it fixed the robot emacs problem I was having.  Will give it some time to see if it reoccurs, but first blush seems like a complete fix.

**Comment by TheQuinbox** [comment]
@devinprater What's the process of changing the speech server like on the Mac? Adding export DTK_PROGRAM=log-mac to .bash_profile?
@robertmeta good to know. That would be very annoying if the case, I depend heavily on Loopback, which uses Rogue Amoeba's ACE, but I'd disable it if it means that I don't have to deal with this issue anymore.

**Comment by devinprater** [comment]
I think you had C-e d d I think, to choose a server.
Devin Prater
***@***.***

**Comment by TheQuinbox** [comment]
I removed Rogue Amoeba's ACE, and have yet to run into either issue. I'll give this a day or two, but if it doesn't come back I'll close this.

**Comment by robertmeta** [comment]
I guess time to hook up a physical loopback ... lol.

**Comment by tvraman** [comment]
Not an Emacspeak issue; this is likely a Mac sound platform issue and should be taken to the right Mac Forum

**Comment by Isaac-Leonard** [comment]
I've been having the issue of the speech cutting out for quite a while now. As far as I'm aware I don't have any audio modifications or custom drivers.
I'ts happened on at least the 2 last and current major versions of MacOS but has been even worse then normal lately.
It seems to only happen in certain modes, for example it happens around every couple minutes when working with java code but barely at all when working with LaTeX.
Reloading emacspeak starts the talking again and more specifically if I run
```
(dtk-initialize)
```
also starts the speech again.
I don't experience this issue with normal voiceover or with other custom screen readers like TDSR even that both use the same voice so I believe it is a emacspeak specific issue.

**Comment by Isaac-Leonard** [comment]
Modifying dtk-make-process to have a buffer asociated with the speaker process gives no output until speech stops in, then it just has:
Process Speaker killed: 9

So Not sure whats killing it but I don't think it's specifically an audio issue

**Comment by Isaac-Leonard** [comment]
So just found the tts-restart command which also works for starting the speech server after it's killed

**Comment by Isaac-Leonard** [comment]
So I did some more fiddling and now have the logs before a crash of the speech server, I've pasted the last 100 ish lines below:
```

queueing voice change: ['voice', 'Karen-premium']


chunk: q {) }
end


Parsing content...

no match in string )


queueing final chunk  rightParen 

Appending text


chunk: d
end


Voice change

set voice to com.apple.voice.premium.en-AU.Karen


say: [[pmod 112.8]]  when
end



chunk: s
end



chunk: s
end



chunk: s
end



chunk: tts_sync_state all 1 0 720
end


tts_sync: set punctuation level to: all capitalize to 0 allcaps 0 splitCaps 1 rate to: 720



chunk: c {[{voice Karen-premium}] }
end


Parsing content...

first: 
effects []
rest None

queueing voice change: ['voice', 'Karen-premium']


chunk: c { [[pmod 42.3]]  [{echo 1 1 10 0.1}]  }
end


Parsing content...

first: [[pmod 42.3]]  
effects []
rest None


chunk: q {indent 3 }
end


Parsing content...

no match in string indent 3


queueing final chunk indent 3

Appending text


chunk: c {[{voice Karen-premium}] }
end


Parsing content...

first: 
effects []
rest None


Process Speaker killed: 9

```
