### ISSUE TITLE
No audio when under cycle-completion-threshold

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#85]
When completions happen inline, for example for M-x, the initial completion is spoken, but then if tab is pressed again to complete the next option it is not spoken. 

Easy to see if you use 

  (setq completion-cycle-threshold t)

----

I am using master (6a4b9d8ec2a16d9ea1733af153a705477c4adbf7.

**Comment by tvraman** [comment]
This is not enough information.

1. Always be specific about what platform and TTS engine you're talking
   about.

2. There are many completion frameworks in Emacs, be specific.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
Sorry -- shot off that bug report half baked, will put in more complete one soon.
