### ISSUE TITLE
(investigation) Robot/Buggy Audio after extended use 

### ISSUE THREAD

**Issue by robertmeta** [tvraman/emacspeak#86]
@tvraman not sure if this belongs here or on the mailing list?

The bug is fairly consistent, with heavy use with lots of overlapping sounds, the voice and synthesizer on MacOS 12+ will get garbled and will not recover until emacs is exited. 

At first, myself and other users expected it might have to do with 3rd party audio modifications on MacOS, and while this does make it more pronounced, it is not the cause, I have confirmed on a few complete install on an M1 Mac Mini.

The next idea was that it was a specific version of Emacs, specifically Emacs-Mac.  Again, this was a contributing factor to the problem, but not the cause.  I produced it with a fresh built Emacs-Plus 28.2. 

So, then I thought it might be the python mac server, so I wrote a new one in Go to see if this was the case, and while building (and using) my new server, the bug came up again.  So it isn't the python mac server.  I might complete the server, it is just really getting started at https://github.com/robertmeta/fastmac -- I still want a faster more easily concurrent server for Mac. 

By pure luck, as I was doing this stuff over the last few weeks I started using and loving Ivy and Swiper.  This was great timing, as I can consistently bug out my sound with Ivy and Swiper witha  couple tries.  It appears to be related to sounds played during typing / using backsapce in like swiper for example.  With enough overlapping / concurrent noises the sound gets blown out.  I am currently investigating the mechanics of how those sounds are played (audio-faces?)... and I will report back here (or the mailing list if a better place).

**Comment by tvraman** [comment]
Use the mailing list so it gets archived. This is most likely an
underlying Max Audio platform issue.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
