### ISSUE TITLE
Make fails.

### ISSUE THREAD

**Issue by didiercolle** [tvraman/emacspeak#90]
$ git checkout master~389 && make clean && make
Previous HEAD position was f7ca8a54f docfix
HEAD is now at 9502d4f53 use keymap-unset
rm -f *.elc  emacspeak-loaddefs.el 
emacs -batch ...
...
emacs -batch -q -no-site-file      -f package-initialize  --eval '(setq file-name-handler-alist nil gc-cons-threshold 64000000  load-source-file-function  nil)'   -l "../lisp"/emacspeak-preamble.el -l "../lisp"/emacspeak-loaddefs.el   -f batch-byte-compile emacspeak-url-template.el
Loading emacspeak-pronounce...

In toplevel form:
emacspeak-url-template.el:64:1: Error: Symbol’s value as variable is void: key
make[1]: *** [Makefile:55: emacspeak-url-template.elc] Error 1
make: *** [Makefile:47: emacspeak] Error 2

While the previous commit seems to work:
$ git checkout master~390 && make clean && make
Previous HEAD position was 9502d4f53 use keymap-unset
HEAD is now at 1d6ee48c6 bytecomp
...
See the NEWS file for a  summary of new features — Control e cap n in Emacs
See Emacspeak Customizations for customizations — control e cap C in Emacs
Read the Emacspeak Manual — Control e TAB in Emacs
To run  this Emacspeak build, add this  line to the top of your .emacs:
(load-file "/home/dcolle/.emacs.d/emacspeak/lisp/emacspeak-setup.el")
    Type make  <engine> [dtk, outloud,  espeak] to build TTS server. 
Package maintainers: see   etc/install.org	 for instructions.

**Comment by robertmeta** [comment]
Does doing "make config" between "make clean" and "make" change anything?

**Comment by tvraman** [comment]
make config generates the loaddefs file if needed. I merged in your
pull-request -- thanks!

--
