### ISSUE TITLE
voxin / outloud - starting outloud server fails, with "no language found"

### ISSUE THREAD

**Issue by okflo** [tvraman/emacspeak#92]
hi, at first let me thank T.V. and all contributors for this great
piece of software!  Being already a heavy emacs user, before having
the need for an audio desktop, emacspeak was the logical solution for
me.

Unfortunately I am currently struggeling getting voxin / outloud to
run with emacspeak.

starting outloud (in emacspeak/servers) results in:

./outloud 
Using SoX
19No language foundtts
    while executing
"load $tclTTS/atcleci.so"
    (file "./outloud" line 451)

(I got emacspeak working with espeak and also dtk-soft, but as I am a
native german speaker, I would prefer outload/voxin with a german
voice).

steps to reproduce:
- OS: archlinux, but also tried current ubuntu, same result
- get current emacs via git and compile & install
- I obtained from voxin.oralux.org the following languages:
  - voxin-american-english-allison-compact-3.4
  - voxin-american-english-allison-high-3.4
  - voxin-german-petra-ml-high-3.4
  - installed them.
  - voxin seems to be installed correctly, as calling voxin-say
    directly in the shell works. Also orca works, and shows the
    installed voice-packages.
- checkout emacspeak via git and get all depended stuff and built it,
  also doing make in servers/linux-outloud

I also tried the installer from
https://github.com/Oralux/emacspeak_voxin_install with same result.

Digging into atcleci.cpp with my limited cpp-knowledge, that the call
to initLanguage(interp, aLanguages, nLanguages); always results in
NODEFINEDCODESET, despite nLanguages gets the correct result of 3
languages installed.

Many thanks for any hints!

best regards - okflo

**Comment by tvraman** [comment]
This  usually means you haven't correctly installed the outloud license
or things have gone wrong and it cant find the eci.ini file that outloud
installs when you install the language license. 
--

**Comment by devinprater** [comment]
You have to get the IBM ViaVoice part of Voxin, not Vocalizer.
Devin Prater
***@***.***
