### ISSUE TITLE
In absence of DTK_PROGRAM Emacs shortcuts are broken and no indication of the problem

### ISSUE THREAD

**Issue by Hi-Angel** [tvraman/emacspeak#95]
I'm just getting started with `emacsspeak`, and I spent quite some time that after building the project with `make config && make` and running a `./runq` my Emacs movement is broken. For example, pressing `backspace` would not delete a character in a buffer or minibuffer, instead it gets ignored.

I turned out to be my bad of not having read further section about having to also build `servers/native-espeak`. However, I think having at least some error message in the minibuffer and `*Messages*` would help with debugging potential situation where for whatever reason the `DTK_PROGRAM` is not working.

# Steps to reproduce

1. Build project with `make config && make`
2. Make sure native-espeak is absent, in particular `make clean -C servers/native-espeak`
3. Run `unset DTK_PROGRAM; ./runq`. At this point Emacs is not supposed to pronounce anything because `DTK_PROGRAM` is missing.
4. Switch to `*Messages*` buffer and read its content

## Expected

There's an error about `DTK_PROGRAM` not working

## Actual

There's no error

**Comment by tvraman** [comment]
that is sadly not possible.


--

**Comment by tvraman** [comment]
RTFM is a pre-req
